[package]
name = "yewtil"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"
description = "Utility crate for Yew"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.9.0"
yewtil-macro = {path = "crates/yewtil-macro"}


[workspace]
members = [
    "crates/yewtil-macro",
    "examples/demo"
]